### PR TITLE
Add basic config files to A3 server.

### PR DESCRIPTION
**Pull request by BrainP4in**
It would be great if you would have a basic configuration up on the creation of an Arma 3 server. Since the installation does not provide one, I thought the image is the best place for it.

- [ ] Requires the egg default values to change as well

### CODE REVIEW

**Comment by parkervcp** [comment]
Why not integrate these into the egg and not the image... So they aren't hard baked into an image someone uses.

https://github.com/parkervcp/eggs/tree/master/arma/arma3

**Comment by BrainP4in** [comment]
Can I just add the config to the egg folder or put it in a separate git repository?

**Comment by parkervcp** [comment]
Add them into the folder for the egg. You will also need to update the install script to pull the files.

**Comment by parkervcp** [comment]
With reading this it also wouldn't work the way you are trying to set it up.

**Comment by BrainP4in** [comment]
Because of the install script overwriting it?

**Comment by BrainP4in** [comment]
Oh, never mind thank you 🤦‍♂️

**Pull request closed without merging**
