### PR TITLE
Debian/dotnet-5

### PR DESCRIPTION
**Pull request by trenutoo**
Updated the dotnet to the latest 5.0 version, nothing special. Tested with Eco egg that uses dotnet.

### CODE REVIEW

**Comment by Lycol50** [comment]
Please Approve

**Comment by gOOvER** [comment]
v1.2.2 is Beta ;)

**Comment by Lycol50** [comment]
> v1.2.2 is Beta ;)

at least it supports the latest among us clients

**Comment by trenutoo** [comment]
> v1.2.2 is Beta ;)

I'm not sure how a specific game version is related to dotnet-5 image if you are referring to Among Us v1.2.2

**Comment by gOOvER** [comment]
> Please Approv

> > v1.2.2 is Beta ;)
> 
> I'm not sure how a specific game version is related to dotnet-5 image if you are referring to Among Us v1.2.2

It's about 1.2.2. Among Us. ;) and this Comment. Have nothing to do with your PR :)

https://github.com/parkervcp/images/pull/57#issuecomment-727209802



> > v1.2.2 is Beta ;)
> 
> at least it supports the latest among us clients

and again: It's Beta ;) Not official Released ;)

**Pull request merged**
