### PR TITLE
generic bot docker image

### PR DESCRIPTION
**Pull request by ghost**
Size of docker image is like 2GB

### CODE REVIEW

**Comment by ghost** [comment]
I will not add new things

**Comment by parkervcp** [comment]
Give me some time to review this.

**Comment by parkervcp** [comment]
What happens if you run an `apt-get clean` at the end of this? That should get you some space back from that alone. Maybe clean up some of the things you download as well.

**Comment by parkervcp** [comment]
Also the `bot.sh` should be named `entrypoint.sh` to at least match the standards.

**Comment by ghost** [comment]
I will close this pr

**Pull request closed without merging**
