### PR TITLE
uMod - Debian Image

### PR DESCRIPTION
**Pull request by J-Pster**
This image was created for the use of uMod, it serves not only for Valheim, but also for other games that will be supported by the uMod compiler in the future, such as Rust.

Inside this image is installed:

- DotNet 5.0
- uMod

Entrypoint.sh sets PATHs for uMod and DotNet, automatically updates the Server, Plugins and Core (By SoftwareNoob) and finally starts the server.

Again, entrypoint.sh is not only for Valheim, but with some modifications, it will work for all games that use uMod.

Dockerhub Repository: https://hub.docker.com/repository/docker/castblacking/umod-valheim

**To Parkervcp:**
Read the message I left for you at: https://github.com/parkervcp/eggs/pull/1010

### CODE REVIEW

**Comment by gOOvER** [comment]
This is the Code of @Software-Noob

https://github.com/parkervcp/images/blob/93766e5dbc70973176a789725941a9c4fda86529/entrypoint.sh

And then you talk about steal your Code :D

**Comment by J-Pster** [comment]
This code is mine :/

**Comment by J-Pster** [comment]
And, entrypoint.sh, Just as it is written here: # This entrypoint.sh is a modification of the entrypoint made by: Software-Noob, to him credit for making differential Auto-Update scheme.

**Comment by gOOvER** [comment]
You NEVER HAD any Dockerfiles ;)

**Review by gOOvER — CHANGES_REQUESTED** [review]
Not needed this Image, because Software-Noob allready pushed a working one. This Image and your egg; both don't work. Stop now this childish shit

**Comment by J-Pster** [comment]
Software-noob is stealing my project.

**Comment by J-Pster** [comment]
> 
> 
> You NEVER HAD any Dockerfiles ;)

Yes, I made a dockerfile, very different from his, and spent hours trying to learn how to make one, and I did.

**Pull request closed without merging**
