### PR TITLE
Eco libs

### PR DESCRIPTION
**Pull request by gOOvER**

### CODE REVIEW

**Comment by gOOvER** [comment]
libgdiplus is needed for running Eco Server

**Comment by danny6167** [comment]
Is there a good reason to not just use the mono image that already has everything that is needed ?

**Comment by gOOvER** [comment]
> Is there a good reason to not just use the mono image that already has everything that is needed ?

Dev recommend dotnet

"For Update 9.0 the server has been migrated to .NET Core 3.0 and can be run on any linux distribution using 'dotnet'"

**Comment by danny6167** [comment]
You don't need to run through mono just because your on the mono image. It just happens to include all the other deps required. Saves creating another image.

**Comment by gOOvER** [comment]
@danny6167 let's discuss about the Egg here:
https://github.com/parkervcp/eggs/pull/683

**Comment by danny6167** [comment]
I see what you have done wrong. You have opened this PR against the master branch instead of the debian_dotnet branch you needed to use.

**Comment by gOOvER** [comment]
I close here for now, for further tests with Mono

**Pull request closed without merging**
