### PR TITLE
Add image (ubuntu with Minetest Deps)

### PR DESCRIPTION
**Pull request by niansa**
Image for: https://github.com/parkervcp/eggs/pull/310

### CODE REVIEW

**Comment by parkervcp** [comment]
Just looking at this now.

You don't need to install adduser. Why couldn't these packages be added to another image?

**Comment by niansa** [comment]
Doesn't /home/container have to be a user "container"?

**Comment by niansa** [comment]
And my problem is finding these packages on alpine :-/

**Comment by parkervcp** [comment]
You based this image on Ubuntu... so why is Alpine the factor here?

**Comment by niansa** [comment]
Because Alpine is a **lot** smaller

**Comment by parkervcp** [comment]
adduser already exists in the image. That is why you don't need to add it. But you aren't using alpine so that doesn't matter.

My original question still stands though "Why not just add the packages to my Ubuntu image or something?"

**Comment by parkervcp** [comment]
@niansa I am going to close this as you haven't replied to my questions over 3 months.

**Pull request closed without merging**
