### PR TITLE
Change 'faketime' to 'faketime:i386'

### PR DESCRIPTION
**Pull request by DJTerrum**
Unfortunately I did not realise that HLDS uses 32-bit so it will need to be altered to use the i386 version of faketime instead. Sorry about that.

### CODE REVIEW

**Comment by parkervcp** [comment]
Why not both the 32 and 64 bit versions?

**Comment by DJTerrum** [comment]
Likelihood is the ubuntu/source image won't need the 64-bit version as HLDS & SRCDS are 32-bit only.

**Comment by parkervcp** [comment]
There are other services that use this image.

**Comment by DJTerrum** [comment]
Fair enough, I thought the 'source' in 'ubuntu/source' meant it was for the Source (HLDS/SRCDS) engine only, but I've added both in for you now.

**Pull request merged**
